version: '3'

services:
  backend:
    build:
      context: ./portfolio-backend
    container_name: laravel-backend
    ports:
      - "8000:80"
    volumes:
      - ./portfolio-backend:/var/www/html
    networks:
      - app-network

  frontend:
    build:
      context: ./portfolio-frontend
    container_name: vue-frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./portfolio-frontend:/app 
      - /app/node_modules 
    command: npm run dev 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - app-network
      
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    ports:
      - "9000:8000" # Woodpecker UI/API
      - "9001:9000" # GRPC port
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:9000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://git.dev.solved.cz/
      - WOODPECKER_GITEA_CLIENT=d7685583-9c5f-4cdd-b334-f39837d7f327
      - WOODPECKER_GITEA_SECRET=Hhbi92SNDLsQ1Pmn2MPXp6pdwdVjXJr_VXjuHGFHlyM=
      - WOODPECKER_AGENT_SECRET=a3c8f79b1c4d47b2a5d8e3f2c1a7b9d4
      - WOODPECKER_ADMIN=admin
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
      - WOODPECKER_GRPC_SECURE=false
      - WOODPECKER_GRPC_ADDR=:9000
      - WOODPECKER_GITEA_SERVER=https://git.dev.solved.cz/
    networks:
      - app-network
      
  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=a3c8f79b1c4d47b2a5d8e3f2c1a7b9d4
      - WOODPECKER_GRPC_SECURE=false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  woodpecker-server-data: