version: '3'

services:
  backend:
    build:
      context: ./portfolio-backend
    container_name: laravel-backend
    ports:
      - "8000:80"
    volumes:
      - ./portfolio-backend:/var/www/html
      - backend-data:/var/www/html/storage # Thêm volume để lưu trữ dữ liệu
    networks:
      - app-network

  frontend:
    build:
      context: ./portfolio-frontend
    container_name: vue-frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./portfolio-frontend:/app 
      - /app/node_modules 
      - frontend-data:/app/public # Thêm volume cho dữ liệu tĩnh của frontend
    command: npm run dev 
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - app-network

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    ports:
      - "9000:8000"
      - "9001:9000"
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker
      - woodpecker-server-config:/etc/woodpecker  # Thêm volume cho cấu hình của Woodpecker
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://localhost:9000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_DATABASE_DRIVER=${WOODPECKER_DATABASE_DRIVER}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_DATABASE_DATASOURCE=${WOODPECKER_DATABASE_DATASOURCE}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GRPC_SECURE=${WOODPECKER_GRPC_SECURE}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GRPC_ADDR=${WOODPECKER_GRPC_ADDR}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GITEA_SKIP_VERIFY=${WOODPECKER_GITEA_SKIP_VERIFY}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_LOG_LEVEL=${WOODPECKER_LOG_LEVEL}  # Sử dụng biến môi trường từ .env
    networks:
      - app-network

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:latest
    container_name: woodpecker-agent
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - woodpecker-agent-config:/etc/woodpecker # Thêm volume cho cấu hình của Woodpecker Agent
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}  # Sử dụng biến môi trường từ .env
      - WOODPECKER_GRPC_SECURE=${WOODPECKER_GRPC_SECURE}  # Sử dụng biến môi trường từ .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  woodpecker-server-data:
  woodpecker-server-config:
  woodpecker-agent-config:
  backend-data:
  frontend-data:
